/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accidentescr;

import java.awt.Color;

/**
 *
 * @author mcv26
 */
public class paginaGrafico extends javax.swing.JFrame {

    /**
     * Creates new form paginaGrafico
     */
    private paginaInicio ventanaInicio;
    public paginaGrafico(paginaInicio ventanaInicio) {
        initComponents();
        this.setTitle("Incidentes de Transito en Costa Rica");
        Color color = new Color(53,60,63);
        this.getContentPane().setBackground(color);
        this.ventanaInicio = ventanaInicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRangoTiempo = new javax.swing.JLabel();
        listRangoTiempo = new java.awt.List();
        labelInvolucrados = new javax.swing.JLabel();
        listInvolucrados = new java.awt.List();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        barraInicio = new javax.swing.JMenuBar();
        pagInicio = new javax.swing.JMenu();
        consultasMenu = new javax.swing.JMenu();
        consultaMapa = new javax.swing.JMenuItem();
        consultaIndicador = new javax.swing.JMenuItem();
        consultaObserver = new javax.swing.JMenuItem();
        acercaMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(53, 60, 63));

        labelRangoTiempo.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelRangoTiempo.setForeground(new java.awt.Color(255, 141, 63));
        labelRangoTiempo.setText("Tipo Indicador");

        listRangoTiempo.setMultipleMode(true);

        labelInvolucrados.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelInvolucrados.setForeground(new java.awt.Color(255, 141, 63));
        labelInvolucrados.setText("Indicador");

        listInvolucrados.setMultipleMode(true);

        btnBuscar.setBackground(new java.awt.Color(213, 214, 210));
        btnBuscar.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 141, 63));
        btnBuscar.setText("Consultar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 244, 191));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("Cuadro Provisional AQUI MAPA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barraInicio.setBackground(new java.awt.Color(213, 214, 210));
        barraInicio.setForeground(new java.awt.Color(255, 141, 63));
        barraInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        pagInicio.setBackground(new java.awt.Color(213, 214, 210));
        pagInicio.setForeground(new java.awt.Color(255, 141, 63));
        pagInicio.setText("Inicio");
        pagInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pagInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagInicioMouseClicked(evt);
            }
        });
        barraInicio.add(pagInicio);

        consultasMenu.setBackground(new java.awt.Color(213, 214, 210));
        consultasMenu.setForeground(new java.awt.Color(255, 141, 63));
        consultasMenu.setText("Consultas ");
        consultasMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        consultaMapa.setBackground(new java.awt.Color(213, 214, 210));
        consultaMapa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaMapa.setForeground(new java.awt.Color(255, 141, 63));
        consultaMapa.setText("Mapa de Incidentes");
        consultaMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMapaActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaMapa);

        consultaIndicador.setBackground(new java.awt.Color(213, 214, 210));
        consultaIndicador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaIndicador.setForeground(new java.awt.Color(255, 141, 63));
        consultaIndicador.setText("Estadisticas por Indicadores ");
        consultaIndicador.setEnabled(false);
        consultaIndicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndicadorActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaIndicador);

        consultaObserver.setBackground(new java.awt.Color(213, 214, 210));
        consultaObserver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaObserver.setForeground(new java.awt.Color(255, 141, 63));
        consultaObserver.setText("Estadisticas dinámicas  ");
        consultaObserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaObserverActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaObserver);

        barraInicio.add(consultasMenu);

        acercaMenu.setBackground(new java.awt.Color(213, 214, 210));
        acercaMenu.setForeground(new java.awt.Color(255, 141, 63));
        acercaMenu.setText("Acerca");
        acercaMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acercaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaMenuMouseClicked(evt);
            }
        });
        barraInicio.add(acercaMenu);

        setJMenuBar(barraInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRangoTiempo)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listRangoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listInvolucrados, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelInvolucrados)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(labelRangoTiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listRangoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelInvolucrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listInvolucrados, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagInicioMouseClicked
        ventanaInicio.setVisible(true);
        ventanaInicio.setEnabled(true);;
        this.dispose();
    }//GEN-LAST:event_pagInicioMouseClicked

    private void consultaMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMapaActionPerformed
        paginaMapa mapa;
        mapa = new paginaMapa(ventanaInicio);
        mapa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaMapaActionPerformed

    private void consultaIndicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndicadorActionPerformed
        paginaGrafico grafico;
        grafico = new paginaGrafico(ventanaInicio);
        grafico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaIndicadorActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void acercaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaMenuMouseClicked
        paginaAcerca acerca;
        acerca = new paginaAcerca(ventanaInicio);
        acerca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_acercaMenuMouseClicked

    private void consultaObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaObserverActionPerformed
        // TODO add your handling code here:
        paginaEstadistica estadistica;
        estadistica = new paginaEstadistica(ventanaInicio);
        estadistica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaObserverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acercaMenu;
    private javax.swing.JMenuBar barraInicio;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JMenuItem consultaIndicador;
    private javax.swing.JMenuItem consultaMapa;
    private javax.swing.JMenuItem consultaObserver;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelInvolucrados;
    private javax.swing.JLabel labelRangoTiempo;
    private java.awt.List listInvolucrados;
    private java.awt.List listRangoTiempo;
    private javax.swing.JMenu pagInicio;
    // End of variables declaration//GEN-END:variables
}
