/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accidentescr;

import Conexion.BDConexion;
import Controller.Controlador;
import Controller.DTOConsulta2;
import Model.RespuestaConsulta2;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author mcv26
 */
public class paginaGrafico extends javax.swing.JFrame {

    /**
     * Creates new form paginaGrafico
     */
    private paginaInicio ventanaInicio;
    DefaultPieDataset dataset;
    Connection conexionBD;
    PreparedStatement statement;
    ArrayList<String> indicadores = new ArrayList(Arrays.asList("EdadQuinquenal","Sexo","Lesion","Rol"));
    ResultSet rs = null;
    public paginaGrafico(paginaInicio ventanaInicio) {
        initComponents();
        this.setTitle("Incidentes de Transito en Costa Rica");
        Color color = new Color(53,60,63);
        this.getContentPane().setBackground(color);
        this.ventanaInicio = ventanaInicio;
        llenadoDatos();
    }
    
    private void llenadoDatos(){
        listTipoIndicador.add("Rango de Edad");
        listTipoIndicador.add("Sexo");
        listTipoIndicador.add("Tipo de Lesión");
        listTipoIndicador.add("Involucrado");
        try {
            conexionBD = BDConexion.obtenerConexion();
        } catch (SQLException ex) {
            Logger.getLogger(paginaGrafico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(paginaGrafico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cerrarConexion(){
        try {
            conexionBD.close();
        } catch (SQLException ex) {
            Logger.getLogger(paginaGrafico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTipoIndicador = new javax.swing.JLabel();
        listTipoIndicador = new java.awt.List();
        labelIndicador = new javax.swing.JLabel();
        listIndicador = new java.awt.List();
        btnBuscar = new javax.swing.JButton();
        panelGrafico = new javax.swing.JPanel();
        barraInicio = new javax.swing.JMenuBar();
        pagInicio = new javax.swing.JMenu();
        consultasMenu = new javax.swing.JMenu();
        consultaMapa = new javax.swing.JMenuItem();
        consultaIndicador = new javax.swing.JMenuItem();
        consultaObserver = new javax.swing.JMenuItem();
        acercaMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(53, 60, 63));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        labelTipoIndicador.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelTipoIndicador.setForeground(new java.awt.Color(255, 141, 63));
        labelTipoIndicador.setText("Tipo Indicador");

        listTipoIndicador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTipoIndicadorMouseClicked(evt);
            }
        });

        labelIndicador.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelIndicador.setForeground(new java.awt.Color(255, 141, 63));
        labelIndicador.setText("Indicador");

        listIndicador.setMultipleMode(true);

        btnBuscar.setBackground(new java.awt.Color(213, 214, 210));
        btnBuscar.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 141, 63));
        btnBuscar.setText("Consultar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        panelGrafico.setBackground(new java.awt.Color(117, 104, 103));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        barraInicio.setBackground(new java.awt.Color(213, 214, 210));
        barraInicio.setForeground(new java.awt.Color(255, 141, 63));
        barraInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        pagInicio.setBackground(new java.awt.Color(213, 214, 210));
        pagInicio.setForeground(new java.awt.Color(255, 141, 63));
        pagInicio.setText("Inicio");
        pagInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pagInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagInicioMouseClicked(evt);
            }
        });
        barraInicio.add(pagInicio);

        consultasMenu.setBackground(new java.awt.Color(213, 214, 210));
        consultasMenu.setForeground(new java.awt.Color(255, 141, 63));
        consultasMenu.setText("Consultas ");
        consultasMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        consultaMapa.setBackground(new java.awt.Color(213, 214, 210));
        consultaMapa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaMapa.setForeground(new java.awt.Color(255, 141, 63));
        consultaMapa.setText("Mapa de Incidentes");
        consultaMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMapaActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaMapa);

        consultaIndicador.setBackground(new java.awt.Color(213, 214, 210));
        consultaIndicador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaIndicador.setForeground(new java.awt.Color(255, 141, 63));
        consultaIndicador.setText("Estadisticas por Indicadores ");
        consultaIndicador.setEnabled(false);
        consultaIndicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndicadorActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaIndicador);

        consultaObserver.setBackground(new java.awt.Color(213, 214, 210));
        consultaObserver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaObserver.setForeground(new java.awt.Color(255, 141, 63));
        consultaObserver.setText("Estadisticas dinámicas  ");
        consultaObserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaObserverActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaObserver);

        barraInicio.add(consultasMenu);

        acercaMenu.setBackground(new java.awt.Color(213, 214, 210));
        acercaMenu.setForeground(new java.awt.Color(255, 141, 63));
        acercaMenu.setText("Acerca");
        acercaMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acercaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaMenuMouseClicked(evt);
            }
        });
        barraInicio.add(acercaMenu);

        setJMenuBar(barraInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoIndicador)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelIndicador))
                    .addComponent(listIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listTipoIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(labelTipoIndicador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listTipoIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(labelIndicador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagInicioMouseClicked
        ventanaInicio.setVisible(true);
        ventanaInicio.setEnabled(true);
        //cerrarConexion();
        this.dispose();
    }//GEN-LAST:event_pagInicioMouseClicked

    private void consultaMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMapaActionPerformed
        paginaMapa mapa;
        mapa = new paginaMapa(ventanaInicio);
        mapa.setVisible(true);
        //cerrarConexion();
        this.dispose();
    }//GEN-LAST:event_consultaMapaActionPerformed

    private void consultaIndicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndicadorActionPerformed
        paginaGrafico grafico;
        grafico = new paginaGrafico(ventanaInicio);
        grafico.setVisible(true);
        //}cerrarConexion();
        this.dispose();
    }//GEN-LAST:event_consultaIndicadorActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       /*Enviar datos y obtener resultset*/
        DTOConsulta2 consulta;
        Controlador controlador = new Controlador();
        String consultaSQL = "";
        ArrayList<RespuestaConsulta2> listaRespuestas = new ArrayList<>();
        dataset = new DefaultPieDataset();
        String indicador = indicadores.get(listTipoIndicador.getSelectedIndex());
        consulta = new DTOConsulta2(indicador, consultaSQL, listaRespuestas);
        controlador.procesarConsulta2(consulta);
        
        listaRespuestas = consulta.getListaRespuestas();
        
        for (int i = 0; i < listaRespuestas.size(); i++) {
            dataset.setValue(listaRespuestas.get(i).getIndicador(), listaRespuestas.get(i).getCount());
        }          
        JFreeChart grafico = ChartFactory.createPieChart3D("Gráfico por tipor de indicador", 
                dataset, true, true, false);
        ChartPanel panel = new ChartPanel(grafico);
        panelGrafico.removeAll();
        panelGrafico.add(panel);
        panel.setBounds(1, 1, panelGrafico.getWidth(), panelGrafico.getHeight());
      
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void acercaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaMenuMouseClicked
        paginaAcerca acerca;
        acerca = new paginaAcerca(ventanaInicio);
        acerca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_acercaMenuMouseClicked

    private void consultaObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaObserverActionPerformed
        // TODO add your handling code here:
        paginaEstadistica estadistica;
        estadistica = new paginaEstadistica(ventanaInicio);
        estadistica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaObserverActionPerformed

    private void listTipoIndicadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTipoIndicadorMouseClicked
        // TODO add your handling code here:
        String sql;
        listIndicador.removeAll();
        if(listTipoIndicador.getSelectedIndex()==0){
            sql = "Select Descripcion from edadquinquenal order by Descripcion";
            try {
                statement = conexionBD.prepareStatement(sql);
                rs = statement.executeQuery();
                while(rs.next()){
                    listIndicador.add(rs.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(paginaGrafico.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        if(listTipoIndicador.getSelectedIndex()==1){
            try {
                sql = "Select Sexo from sexo";
                statement = conexionBD.prepareStatement(sql);
                rs = statement.executeQuery();
                while(rs.next()){
                    listIndicador.add(rs.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(paginaGrafico.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        if(listTipoIndicador.getSelectedIndex()==2){
            try {
                sql = "Select Tipo from lesion";
                statement = conexionBD.prepareStatement(sql);
                rs = statement.executeQuery();
                while(rs.next()){
                    listIndicador.add(rs.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(paginaGrafico.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        if(listTipoIndicador.getSelectedIndex()==3){
            try {
                sql = "Select Rol from rol";
                statement = conexionBD.prepareStatement(sql);
                rs = statement.executeQuery();
                while(rs.next()){
                    listIndicador.add(rs.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(paginaGrafico.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_listTipoIndicadorMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //cerrarConexion();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acercaMenu;
    private javax.swing.JMenuBar barraInicio;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JMenuItem consultaIndicador;
    private javax.swing.JMenuItem consultaMapa;
    private javax.swing.JMenuItem consultaObserver;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JLabel labelIndicador;
    private javax.swing.JLabel labelTipoIndicador;
    private java.awt.List listIndicador;
    private java.awt.List listTipoIndicador;
    private javax.swing.JMenu pagInicio;
    private javax.swing.JPanel panelGrafico;
    // End of variables declaration//GEN-END:variables
}
