/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accidentescr;

import Model.RespuestaConsulta1;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author mcv26
 */
public class paginaMapa extends javax.swing.JFrame {

    /**
     * Creates new form paginaMapa
     */
    private paginaInicio ventanaInicio;
    public paginaMapa(paginaInicio ventanaInicio) {
        initComponents();
        this.setTitle("Incidentes de Transito en Costa Rica");
        Color color = new Color(53,60,63);
        this.getContentPane().setBackground(color);
        this.ventanaInicio = ventanaInicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProvincia = new javax.swing.JLabel();
        labelCanton = new javax.swing.JLabel();
        listProvincia = new java.awt.List();
        listCanton = new java.awt.List();
        labelDistrito = new javax.swing.JLabel();
        listDistrito = new java.awt.List();
        labelRangoTiempo = new javax.swing.JLabel();
        listRangoTiempo = new java.awt.List();
        labelInvolucrados = new javax.swing.JLabel();
        listInvolucrados = new java.awt.List();
        labelSexo = new javax.swing.JLabel();
        listSexo = new java.awt.List();
        labelTipoLesion = new javax.swing.JLabel();
        listTipoLesion = new java.awt.List();
        labelRangoEdad = new javax.swing.JLabel();
        listRangoEdad = new java.awt.List();
        jPanelMap = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        barraInicio = new javax.swing.JMenuBar();
        pagInicio = new javax.swing.JMenu();
        consultasMenu = new javax.swing.JMenu();
        consultaMapa = new javax.swing.JMenuItem();
        consultaIndicador = new javax.swing.JMenuItem();
        consultaObserver = new javax.swing.JMenuItem();
        acercaMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(53, 60, 63));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        labelProvincia.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelProvincia.setForeground(new java.awt.Color(255, 141, 63));
        labelProvincia.setText("Provincia");

        labelCanton.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelCanton.setForeground(new java.awt.Color(255, 141, 63));
        labelCanton.setText("Cantón ");

        listProvincia.setMultipleMode(true);

        listCanton.setMultipleMode(true);

        labelDistrito.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelDistrito.setForeground(new java.awt.Color(255, 141, 63));
        labelDistrito.setText("Distrito");

        listDistrito.setMultipleMode(true);

        labelRangoTiempo.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelRangoTiempo.setForeground(new java.awt.Color(255, 141, 63));
        labelRangoTiempo.setText("Rango De Tiempo");

        listRangoTiempo.setMultipleMode(true);

        labelInvolucrados.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelInvolucrados.setForeground(new java.awt.Color(255, 141, 63));
        labelInvolucrados.setText("Involucrados");

        listInvolucrados.setMultipleMode(true);

        labelSexo.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelSexo.setForeground(new java.awt.Color(255, 141, 63));
        labelSexo.setText("Sexo");

        listSexo.setMultipleMode(true);

        labelTipoLesion.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelTipoLesion.setForeground(new java.awt.Color(255, 141, 63));
        labelTipoLesion.setText("Tipo Lesión");

        listTipoLesion.setMultipleMode(true);

        labelRangoEdad.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        labelRangoEdad.setForeground(new java.awt.Color(255, 141, 63));
        labelRangoEdad.setText("Rangos Edad");

        listRangoEdad.setMultipleMode(true);

        jPanelMap.setBackground(new java.awt.Color(117, 104, 103));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("Cuadro Provisional AQUI MAPA");

        javax.swing.GroupLayout jPanelMapLayout = new javax.swing.GroupLayout(jPanelMap);
        jPanelMap.setLayout(jPanelMapLayout);
        jPanelMapLayout.setHorizontalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMapLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMapLayout.setVerticalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMapLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        btnBuscar.setBackground(new java.awt.Color(213, 214, 210));
        btnBuscar.setFont(new java.awt.Font("Trajan Pro", 3, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 141, 63));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        barraInicio.setBackground(new java.awt.Color(213, 214, 210));
        barraInicio.setForeground(new java.awt.Color(255, 141, 63));
        barraInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        pagInicio.setBackground(new java.awt.Color(213, 214, 210));
        pagInicio.setForeground(new java.awt.Color(255, 141, 63));
        pagInicio.setText("Inicio");
        pagInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pagInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagInicioMouseClicked(evt);
            }
        });
        barraInicio.add(pagInicio);

        consultasMenu.setBackground(new java.awt.Color(213, 214, 210));
        consultasMenu.setForeground(new java.awt.Color(255, 141, 63));
        consultasMenu.setText("Consultas ");
        consultasMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        consultaMapa.setBackground(new java.awt.Color(213, 214, 210));
        consultaMapa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaMapa.setForeground(new java.awt.Color(255, 141, 63));
        consultaMapa.setText("Mapa de Incidentes");
        consultaMapa.setEnabled(false);
        consultaMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMapaActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaMapa);

        consultaIndicador.setBackground(new java.awt.Color(213, 214, 210));
        consultaIndicador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaIndicador.setForeground(new java.awt.Color(255, 141, 63));
        consultaIndicador.setText("Estadisticas por Indicadores ");
        consultaIndicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndicadorActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaIndicador);

        consultaObserver.setBackground(new java.awt.Color(213, 214, 210));
        consultaObserver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaObserver.setForeground(new java.awt.Color(255, 141, 63));
        consultaObserver.setText("Estadisticas dinámicas  ");
        consultaObserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaObserverActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaObserver);

        barraInicio.add(consultasMenu);

        acercaMenu.setBackground(new java.awt.Color(213, 214, 210));
        acercaMenu.setForeground(new java.awt.Color(255, 141, 63));
        acercaMenu.setText("Acerca");
        acercaMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acercaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaMenuMouseClicked(evt);
            }
        });
        barraInicio.add(acercaMenu);

        setJMenuBar(barraInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listInvolucrados, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInvolucrados)
                            .addComponent(listSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listTipoLesion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listRangoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelTipoLesion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelRangoEdad))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jPanelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRangoTiempo)
                            .addComponent(listRangoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelProvincia)
                            .addComponent(listProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCanton))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(labelDistrito))
                            .addComponent(listDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(labelDistrito)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(listDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelCanton)
                                .addComponent(labelProvincia))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(listProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(listCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelRangoTiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listRangoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInvolucrados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listInvolucrados, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(labelSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelTipoLesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listTipoLesion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(labelRangoEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listRangoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaMapaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.setAlwaysOnTop(false); //dejar este línea para que no tenga problemas con la nueva ventana de mapa
        
        Mapa mapa;
        RespuestaConsulta1 res = new RespuestaConsulta1("9 56 11","-84 4 28", 2);
        RespuestaConsulta1 res2 = new RespuestaConsulta1("09 54 00","-84 04 01", 5);
        ArrayList arr = new ArrayList<RespuestaConsulta1>();
        arr.add(res);
        arr.add(res2);
        mapa = new Mapa("Prueba",arr);
        System.out.println("vo");
        mapa.setVisible(true);
        
        /*paginaMapa mapa;
        mapa = new paginaMapa(this);
        mapa.setVisible(true);
        this.setVisible(false);
        this.setEnabled(false);*/
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void pagInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagInicioMouseClicked
        ventanaInicio.setVisible(true);
        ventanaInicio.setEnabled(true);;
        this.dispose();
    }//GEN-LAST:event_pagInicioMouseClicked

    private void consultaIndicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndicadorActionPerformed
        paginaGrafico grafico;
        grafico = new paginaGrafico(ventanaInicio);
        grafico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaIndicadorActionPerformed

    private void acercaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaMenuMouseClicked
        paginaAcerca acerca;
        acerca = new paginaAcerca(ventanaInicio);
        acerca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_acercaMenuMouseClicked

    private void consultaObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaObserverActionPerformed
        // TODO add your handling code here:
        paginaEstadistica estadistica;
        estadistica = new paginaEstadistica(ventanaInicio);
        estadistica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaObserverActionPerformed
 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acercaMenu;
    private javax.swing.JMenuBar barraInicio;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JMenuItem consultaIndicador;
    private javax.swing.JMenuItem consultaMapa;
    private javax.swing.JMenuItem consultaObserver;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JPanel jPanelMap;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCanton;
    private javax.swing.JLabel labelDistrito;
    private javax.swing.JLabel labelInvolucrados;
    private javax.swing.JLabel labelProvincia;
    private javax.swing.JLabel labelRangoEdad;
    private javax.swing.JLabel labelRangoTiempo;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTipoLesion;
    private java.awt.List listCanton;
    private java.awt.List listDistrito;
    private java.awt.List listInvolucrados;
    private java.awt.List listProvincia;
    private java.awt.List listRangoEdad;
    private java.awt.List listRangoTiempo;
    private java.awt.List listSexo;
    private java.awt.List listTipoLesion;
    private javax.swing.JMenu pagInicio;
    // End of variables declaration//GEN-END:variables
}
