/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accidentescr;

/**
 *
 * @author mcv26
 */
public class paginaEstadistica extends javax.swing.JFrame {

    /**
     * Creates new form paginaEstadistica
     */
    paginaInicio ventanaInicio;
    public paginaEstadistica(paginaInicio ventanaInicio) {
        initComponents();
        this.ventanaInicio = ventanaInicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraInicio = new javax.swing.JMenuBar();
        pagInicio = new javax.swing.JMenu();
        consultasMenu = new javax.swing.JMenu();
        consultaMapa = new javax.swing.JMenuItem();
        consultaIndicador = new javax.swing.JMenuItem();
        consultaObserver = new javax.swing.JMenuItem();
        acercaMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        barraInicio.setBackground(new java.awt.Color(213, 214, 210));
        barraInicio.setForeground(new java.awt.Color(255, 141, 63));
        barraInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        pagInicio.setBackground(new java.awt.Color(213, 214, 210));
        pagInicio.setForeground(new java.awt.Color(255, 141, 63));
        pagInicio.setText("Inicio");
        pagInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pagInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagInicioMouseClicked(evt);
            }
        });
        barraInicio.add(pagInicio);

        consultasMenu.setBackground(new java.awt.Color(213, 214, 210));
        consultasMenu.setForeground(new java.awt.Color(255, 141, 63));
        consultasMenu.setText("Consultas ");
        consultasMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        consultaMapa.setBackground(new java.awt.Color(213, 214, 210));
        consultaMapa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaMapa.setForeground(new java.awt.Color(255, 141, 63));
        consultaMapa.setText("Mapa de Incidentes");
        consultaMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMapaActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaMapa);

        consultaIndicador.setBackground(new java.awt.Color(213, 214, 210));
        consultaIndicador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaIndicador.setForeground(new java.awt.Color(255, 141, 63));
        consultaIndicador.setText("Estadisticas por Indicadores ");
        consultaIndicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndicadorActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaIndicador);

        consultaObserver.setBackground(new java.awt.Color(213, 214, 210));
        consultaObserver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        consultaObserver.setForeground(new java.awt.Color(255, 141, 63));
        consultaObserver.setText("Estadisticas dinámicas  ");
        consultaObserver.setEnabled(false);
        consultaObserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaObserverActionPerformed(evt);
            }
        });
        consultasMenu.add(consultaObserver);

        barraInicio.add(consultasMenu);

        acercaMenu.setBackground(new java.awt.Color(213, 214, 210));
        acercaMenu.setForeground(new java.awt.Color(255, 141, 63));
        acercaMenu.setText("Acerca");
        acercaMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acercaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaMenuMouseClicked(evt);
            }
        });
        barraInicio.add(acercaMenu);

        setJMenuBar(barraInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagInicioMouseClicked
        ventanaInicio.setVisible(true);
        ventanaInicio.setEnabled(true);;
        this.dispose();
    }//GEN-LAST:event_pagInicioMouseClicked

    private void consultaMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMapaActionPerformed
        paginaMapa mapa;
        mapa = new paginaMapa(ventanaInicio);
        mapa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaMapaActionPerformed

    private void consultaIndicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndicadorActionPerformed
        paginaGrafico grafico;
        grafico = new paginaGrafico(ventanaInicio);
        grafico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaIndicadorActionPerformed

    private void consultaObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaObserverActionPerformed
        // TODO add your handling code here:
        paginaEstadistica estadistica;
        estadistica = new paginaEstadistica(ventanaInicio);
        estadistica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultaObserverActionPerformed

    private void acercaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaMenuMouseClicked
        paginaAcerca acerca;
        acerca = new paginaAcerca(ventanaInicio);
        acerca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_acercaMenuMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acercaMenu;
    private javax.swing.JMenuBar barraInicio;
    private javax.swing.JMenuItem consultaIndicador;
    private javax.swing.JMenuItem consultaMapa;
    private javax.swing.JMenuItem consultaObserver;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JMenu pagInicio;
    // End of variables declaration//GEN-END:variables
}
